// File generated by FlutterFire CLI — project insighted-42893
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJZl8IBwxzMtobUhwY7xJvlYqrJYATnU4',
    appId: '1:875605851923:web:4a2f33ff8d86dfce9ba4e6',
    messagingSenderId: '875605851923',
    projectId: 'insighted-42893',
    authDomain: 'insighted-42893.firebaseapp.com',
    storageBucket: 'insighted-42893.firebasestorage.app',
    measurementId: 'G-VNNNCDP4FR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjz5pXbRes_ep5AJjvbGTIbs20u537pEE',
    appId: '1:875605851923:android:75c34fdf11c42bab9ba4e6',
    messagingSenderId: '875605851923',
    projectId: 'insighted-42893',
    storageBucket: 'insighted-42893.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAufRyGKooCsPvVvurCkFgDIXHO_GKMxiE',
    appId: '1:875605851923:ios:53fe5ec75e9f3b519ba4e6',
    messagingSenderId: '875605851923',
    projectId: 'insighted-42893',
    storageBucket: 'insighted-42893.firebasestorage.app',
    iosBundleId: 'com.example.insightEdMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAufRyGKooCsPvVvurCkFgDIXHO_GKMxiE',
    appId: '1:875605851923:ios:53fe5ec75e9f3b519ba4e6',
    messagingSenderId: '875605851923',
    projectId: 'insighted-42893',
    storageBucket: 'insighted-42893.firebasestorage.app',
    iosBundleId: 'com.example.insightEdMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJZl8IBwxzMtobUhwY7xJvlYqrJYATnU4',
    appId: '1:875605851923:web:5c6ab40547655b1a9ba4e6',
    messagingSenderId: '875605851923',
    projectId: 'insighted-42893',
    authDomain: 'insighted-42893.firebaseapp.com',
    storageBucket: 'insighted-42893.firebasestorage.app',
    measurementId: 'G-G4P5QNDP81',
  );
}
